### PR TITLE
adding gha

### PR DESCRIPTION
**Pull request by noah-yoshida**
Adding in github actions to run unit test suite whenever branch is pushed to, or a pull request is opened against said branch.

### CODE REVIEW

**Comment by pbui** [comment]
Can you make it so it runs pylint on all the files and checks that there are no errors?

I think a basic syntax check would actually be helpful

**Comment by noah-yoshida** [comment]
sure thing!

**Comment by noah-yoshida** [comment]
Added pylint to the action - I configured it to only error on actual code errors - there were tons of styling errors it was throwing that would have failed the action otherwise.

**Comment by pbui** [comment]
TYFYS

**Pull request merged**
